start: "su -c 'cd /data/adb/mihomo && chmod +x ./mihomo && nohup ./mihomo -d . >/dev/null 2>&1 &'"
#mihomo启动命令
kill: "su -c 'killall mihomo'"
#mihomo停止命令
check: "su -c 'ps -p $(pidof mihomo) -o pid,ppid,%cpu,%mem,cmd; cat /proc/$(pidof mihomo)/status'"
#查看mihomo状态
ua: "clash.meta"
#下载订阅时使用的User-Agent
port: "9090"
#软件打开的控制端口,需要和配置中的端口对应
timeout: 3
#下载订阅超时,秒
selected: example
#当前选中的订阅的ID
url: "https://www.google.com"
#节点测速链接
testtimeout: "2000"
#节点测速超时,毫秒