name: ClashRoot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 下载代码
        uses: actions/checkout@v6

      - name: 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'

      - name: 安装依赖
        run: flutter pub get

      - name: Build APK (按 ABI 分割)
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      - name: 上传 arm64-v8a APK
        uses: actions/upload-artifact@v7
        with:
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          archive: false